## architecture
arch: SK_GS
arch_cfg:
    use_official_gaussians_render: true
    sh_degree: 3
    loss_cfg:
        image: {method: l1, lambda: 0.8}
        ssim: 0.2 # lambda_dssim
        re_sp_pos: 0
        re_sp_tr: 0
        sp_arap_t: 0.1
        sp_arap_ct: 0
        joint: 0
        joint_all: 0
        jp_dist: 0
        sparse: 0.2
        smooth: 1
        guided: 0
        cmp_p: 1
        cmp_r: 1
        gj: 0
    sp_deform_net_cfg:
        pos_enc_p: 'freq'
        pos_enc_p_cfg: {degree: 10}
        pos_enc_t: 'freq'
        pos_enc_t_cfg: {degree: 6}
        width: 256
        depth: 8
        skips: [4,]
    sk_deform_net_cfg:
        pos_enc_p: 'freq'
        pos_enc_p_cfg: {degree: 10}
        pos_enc_t: 'freq'
        pos_enc_t_cfg: {degree: 6}
        width: 256
        depth: 8
        skips: [4,]
    train_schedule:
        - [0, 'static']
        - [1000, 'sp']
    num_superpoints: 512
    sp_knn_num: 5
    sp_prune_threshold: 0.001
    sp_split_threshold: 0.0002
    sp_merge_threshold: 0.005
    momentum: 0.9
    
    sk_knn_num: 5
    sk_use_features: true
    joint_update_interval: [-1, 10_000]
    test_time_interpolate: false
    loss_arap_start_step: 15000
    gs_knn_update_interval: [1000, 3000]
    adaptive_control_cfg:
        opacity_reset_interval: [3000, 1000, 15000]
        densify_interval: [100, 600, 15000]
        prune_interval: [100, 600, 15000] # 100
        sp_adjust_interval: [-1, 3000, 20_000]
        sp_merge_interval: [-1, 10_000, 20_000]

        densify_grad_threshold: 0.0002
        densify_percent_dense: 0.01
        prune_opacity_threshold: 0.005
        prune_max_screen_size: 20
        prune_percent_dense: 0.1
## dataset
dataset_root: ./data
## solver

num_init_points: 10000

optimizer: adam
optimizer_cfg:
    eps: 1.0e-15
    betas: [0.9, 0.999]

epochs: 30_000
lr: 1.0e-3
lr_schedulers:
    - ['exp', 30_000, 1.0, 0.1] # only for position
eval_interval: 5_000
vis_interval: 1000
checkpoint_interval: 5_000
metric: image/PSNR
metrics: [image, loss]
metric_goal: max